# Generated by Django 5.0.1 on 2024-02-05 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='teacher_photo/')),
                ('subject_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.subject_model')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=9)),
                ('about', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=120)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.subject_model')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.teacher_model')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='product_photos')),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='B2', max_length=2)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='models.teacher_model')),
            ],
        ),
    ]
